volumes:
  dtc_postgres_volume_local:  # Define the named volume here

# services mentioned in the compose file auto become part of the same network!
services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "dtc_postgres_volume_local:/var/lib/postgresql/data:rw"
    ports:
      - "5431:5432"
    networks:
      - airflow-ext

  # pg-Admin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - "8080:80"


# To connect the 2 docker-compose files :
networks:
  airflow-ext:
    external:
      name: dtc-de_default